import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const currentDir = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(currentDir, "..");
const envPath = path.join(rootDir, ".env.local");
const marker = "# Generated by PatchMap local setup";

function getRunnerCommand(name) {
  return process.platform === "win32" ? `${name}.cmd` : name;
}

function runCommand(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: rootDir,
    encoding: "utf8",
    stdio: options.captureOutput ? "pipe" : "inherit",
    ...options,
  });

  if (result.status !== 0) {
    const detail = result.stderr?.trim() || result.stdout?.trim();
    throw new Error(detail || `${command} ${args.join(" ")} failed`);
  }

  return result;
}

function ensureSupabaseCli() {
  try {
    runCommand(getRunnerCommand("npx"), ["supabase", "--version"], { captureOutput: true });
  } catch {
    throw new Error(
      "Supabase CLI is required. Install it or make sure `npx supabase --version` works, then rerun `npm run local:setup`."
    );
  }
}

function parseDotEnv(raw) {
  const values = new Map();

  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }

    const separatorIndex = trimmed.indexOf("=");
    if (separatorIndex === -1) {
      continue;
    }

    const key = trimmed.slice(0, separatorIndex).trim();
    const value = trimmed.slice(separatorIndex + 1);
    values.set(key, value);
  }

  return values;
}

function backupExistingEnv(existingContent) {
  if (!existingContent || existingContent.includes(marker)) {
    return null;
  }

  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  const backupPath = `${envPath}.backup-${timestamp}`;
  fs.copyFileSync(envPath, backupPath);
  return backupPath;
}

function readExistingEnv() {
  if (!fs.existsSync(envPath)) {
    return { content: null, values: new Map() };
  }

  const content = fs.readFileSync(envPath, "utf8");
  return { content, values: parseDotEnv(content) };
}

function getSupabaseEnv() {
  const result = runCommand(
    getRunnerCommand("npx"),
    ["supabase", "status", "-o", "env"],
    { captureOutput: true }
  );

  const values = parseDotEnv(result.stdout);
  const apiUrl = values.get("API_URL");
  const anonKey = values.get("ANON_KEY");
  const serviceRoleKey = values.get("SERVICE_ROLE_KEY");

  if (!apiUrl || !anonKey || !serviceRoleKey) {
    throw new Error(
      "Could not read Supabase local credentials from `supabase status -o env`."
    );
  }

  return { apiUrl, anonKey, serviceRoleKey };
}

function createCredentialKey(existingValues) {
  return (
    existingValues.get("CREDENTIAL_ENCRYPTION_KEY") ??
    crypto.randomBytes(32).toString("base64")
  );
}

function writeEnvFile(existingValues, supabaseEnv) {
  const lines = [
    marker,
    "# Safe for local development. Do not reuse in shared environments.",
    `NEXT_PUBLIC_SUPABASE_URL=${supabaseEnv.apiUrl}`,
    `NEXT_PUBLIC_SUPABASE_ANON_KEY=${supabaseEnv.anonKey}`,
    `SUPABASE_SERVICE_ROLE_KEY=${supabaseEnv.serviceRoleKey}`,
    `CREDENTIAL_ENCRYPTION_KEY=${createCredentialKey(existingValues)}`,
    `ALLOW_PROVIDER_TOKEN_FALLBACK=${existingValues.get("ALLOW_PROVIDER_TOKEN_FALLBACK") ?? "true"}`,
    "",
    "# Optional provider fallbacks for imports inside your network.",
    `GITHUB_TOKEN=${existingValues.get("GITHUB_TOKEN") ?? ""}`,
    `GITLAB_BASE_URL=${existingValues.get("GITLAB_BASE_URL") ?? ""}`,
    `GITLAB_TOKEN=${existingValues.get("GITLAB_TOKEN") ?? ""}`,
    "",
    "# Optional GitHub App settings. Leave blank for local-only use.",
    `GITHUB_APP_ID=${existingValues.get("GITHUB_APP_ID") ?? ""}`,
    `GITHUB_APP_SLUG=${existingValues.get("GITHUB_APP_SLUG") ?? ""}`,
    `GITHUB_APP_PRIVATE_KEY=${existingValues.get("GITHUB_APP_PRIVATE_KEY") ?? ""}`,
    "",
  ];

  fs.writeFileSync(envPath, `${lines.join("\n")}`, "utf8");
}

function main() {
  ensureSupabaseCli();

  console.log("Starting local Supabase services...");
  runCommand(getRunnerCommand("npx"), ["supabase", "start"]);

  console.log("Applying migrations to the local database...");
  runCommand(getRunnerCommand("npx"), ["supabase", "db", "reset", "--local", "--yes"]);

  const existingEnv = readExistingEnv();
  const backupPath = backupExistingEnv(existingEnv.content);
  const supabaseEnv = getSupabaseEnv();

  writeEnvFile(existingEnv.values, supabaseEnv);

  if (backupPath) {
    console.log(`Backed up the previous .env.local to ${path.basename(backupPath)}.`);
  }

  console.log("Local setup is ready.");
  console.log("Next steps:");
  console.log("  1. Optionally fill in GITLAB_BASE_URL or provider tokens in .env.local.");
  console.log("  2. Run npm run local:start");
  console.log("  3. Open http://127.0.0.1:3000 and create an account.");
}

main();
