type PatchMapMarkdownSummary = {
  purpose?: string | null;
  behaviorChangeNotes?: string | null;
  riskNotes?: string | null;
  testNotes?: string | null;
} | null;

type PatchMapMarkdownGroup = {
  title: string;
  description?: string | null;
  filePaths: string[];
  orderIndex: number;
};

export type GeneratePatchMapMarkdownInput = {
  summary: PatchMapMarkdownSummary;
  groups: PatchMapMarkdownGroup[];
};

function addSection(lines: string[], heading: string, value?: string | null) {
  const trimmed = value?.trim();
  if (!trimmed) return;

  lines.push(`### ${heading}`);
  lines.push(trimmed);
  lines.push("");
}

function normalizeGroups(
  groups: PatchMapMarkdownGroup[]
): PatchMapMarkdownGroup[] {
  return [...groups].sort((a, b) => a.orderIndex - b.orderIndex);
}

export function generatePatchMapMarkdown(
  input: GeneratePatchMapMarkdownInput
): string {
  const lines: string[] = [];

  lines.push("<!-- PATCHMAP:START -->");
  lines.push("## PatchMap");
  lines.push("");

  addSection(lines, "Purpose", input.summary?.purpose);
  addSection(lines, "Behavior Change", input.summary?.behaviorChangeNotes);
  addSection(lines, "Risk", input.summary?.riskNotes);
  addSection(lines, "Tests", input.summary?.testNotes);

  const groups = normalizeGroups(input.groups);

  if (groups.length > 0) {
    lines.push("---");
    lines.push("");
    lines.push("## Change Walkthrough");
    lines.push("");

    groups.forEach((group, index) => {
      lines.push(`### ${index + 1}. ${group.title}`);

      const description = group.description?.trim();
      if (description) {
        lines.push(description);
        lines.push("");
      }

      if (group.filePaths.length > 0) {
        lines.push("**Files**");
        group.filePaths.forEach((filePath) => {
          lines.push(`- \`${filePath}\``);
        });
        lines.push("");
      }
    });
  }

  lines.push("---");
  lines.push("");
  lines.push("_Generated by PatchMap_");
  lines.push("<!-- PATCHMAP:END -->");

  return lines.join("\n").trim();
}
